#!/usr/bin/env python3
"""
build_panel.py — ESP32-S3 Admin Panel Builder
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Gzips every file in the data/ folder and writes them as C byte arrays
into admin_panel.h so the firmware can serve them directly from flash.

Usage (run from the sketch folder):
    python build_panel.py

Output:
    admin_panel.h   — include this in your .ino, never edit by hand

Run this whenever you change any file in data/, then re-upload the sketch.
No LittleFS plugin needed.
"""

import gzip, os, sys

DATA_DIR  = os.path.join(os.path.dirname(__file__), 'data')
OUT_FILE  = os.path.join(os.path.dirname(__file__), 'admin_panel.h')

# Map file extensions to MIME types
MIME = {
    '.html': 'text/html; charset=utf-8',
    '.css':  'text/css',
    '.js':   'application/javascript',
    '.json': 'application/json',
    '.png':  'image/png',
    '.jpg':  'image/jpeg',
    '.ico':  'image/x-icon',
    '.svg':  'image/svg+xml',
    '.bin':  'application/octet-stream',
}

def to_c_name(filename):
    """Convert filename to a valid C identifier.  e.g. admin.html → admin_html"""
    return filename.replace('.', '_').replace('-', '_').replace(' ', '_')

def ext(filename):
    return os.path.splitext(filename)[1].lower()

def main():
    if not os.path.isdir(DATA_DIR):
        print(f"ERROR: data/ folder not found at {DATA_DIR}")
        sys.exit(1)

    files = sorted(f for f in os.listdir(DATA_DIR)
                   if os.path.isfile(os.path.join(DATA_DIR, f)))

    if not files:
        print("ERROR: data/ folder is empty")
        sys.exit(1)

    lines = []
    lines.append('// ─────────────────────────────────────────────────────────')
    lines.append('// admin_panel.h — AUTO-GENERATED by build_panel.py')
    lines.append('// DO NOT EDIT — run build_panel.py to regenerate')
    lines.append('// ─────────────────────────────────────────────────────────')
    lines.append('#pragma once')
    lines.append('#include <pgmspace.h>')
    lines.append('')

    route_entries = []  # (url_path, c_name, mime, size)

    total_raw = 0
    total_gz  = 0

    for filename in files:
        path     = os.path.join(DATA_DIR, filename)
        raw      = open(path, 'rb').read()
        gz       = gzip.compress(raw, compresslevel=9)
        c_name   = to_c_name(filename)
        mime     = MIME.get(ext(filename), 'application/octet-stream')
        url      = '/' + filename

        total_raw += len(raw)
        total_gz  += len(gz)

        print(f"  {filename:30s}  {len(raw):6d} → {len(gz):5d} bytes  ({100*len(gz)//len(raw)}%)")

        # Write byte array
        lines.append(f'// {filename}  ({len(raw)} bytes raw → {len(gz)} bytes gzip)')
        lines.append(f'static const uint8_t _{c_name}[] PROGMEM = {{')

        hex_bytes = [f'0x{b:02x}' for b in gz]
        # 16 bytes per line
        for i in range(0, len(hex_bytes), 16):
            chunk = hex_bytes[i:i+16]
            lines.append('  ' + ', '.join(chunk) + ',')

        lines.append('};')
        lines.append(f'static const size_t _{c_name}_len = {len(gz)};')
        lines.append('')

        route_entries.append((url, c_name, mime, len(gz)))

    # Write the registration function
    lines.append('// Call this once in initRoutes() to register all admin panel files.')
    lines.append('// The server argument is your AsyncWebServer instance.')
    lines.append('inline void registerAdminPanel(AsyncWebServer &server) {')

    # Sort so /admin/style.css is registered before /admin to avoid prefix matching
    route_entries.sort(key=lambda x: (0 if x[0] == '/style.css' else 1, x[0]))

    for url, c_name, mime, size in route_entries:
        # admin.html → served at /admin and /admin.html
        if url == '/admin.html':
            for route in ['/admin', '/admin.html']:
                lines.append(f'  // {route}')
                lines.append(f'  server.on("{route}", HTTP_GET, [](AsyncWebServerRequest *req) {{')
                lines.append(f'    AsyncWebServerResponse *r = req->beginResponse_P(200, F("{mime}"), _{c_name}, _{c_name}_len);')
                lines.append(f'    r->addHeader(F("Content-Encoding"), F("gzip"));')
                lines.append(f'    r->addHeader(F("Cache-Control"), F("no-cache"));')
                lines.append(f'    req->send(r);')
                lines.append(f'  }});')
                lines.append('')
        # style.css → served at /admin/style.css only
        elif url == '/style.css':
            lines.append(f'  // /admin/style.css (protected under /admin/ prefix)')
            lines.append(f'  server.on("/admin/style.css", HTTP_GET, [](AsyncWebServerRequest *req) {{')
            lines.append(f'    AsyncWebServerResponse *r = req->beginResponse_P(200, F("{mime}"), _{c_name}, _{c_name}_len);')
            lines.append(f'    r->addHeader(F("Content-Encoding"), F("gzip"));')
            lines.append(f'    r->addHeader(F("Cache-Control"), F("no-cache"));')
            lines.append(f'    req->send(r);')
            lines.append(f'  }});')
            lines.append('')
        # Skip index.html — firmware handles / with LittleFS/SD priority
        elif url == '/index.html':
            lines.append(f'  // {url} (root / handled by firmware with LittleFS/SD priority)')
            lines.append(f'  server.on("{url}", HTTP_GET, [](AsyncWebServerRequest *req) {{')
            lines.append(f'    AsyncWebServerResponse *r = req->beginResponse_P(200, F("{mime}"), _{c_name}, _{c_name}_len);')
            lines.append(f'    r->addHeader(F("Content-Encoding"), F("gzip"));')
            lines.append(f'    r->addHeader(F("Cache-Control"), F("no-cache"));')
            lines.append(f'    req->send(r);')
            lines.append(f'  }});')
            lines.append('')
        else:
            lines.append(f'  // {url}')
            lines.append(f'  server.on("{url}", HTTP_GET, [](AsyncWebServerRequest *req) {{')
            lines.append(f'    AsyncWebServerResponse *r = req->beginResponse_P(200, F("{mime}"), _{c_name}, _{c_name}_len);')
            lines.append(f'    r->addHeader(F("Content-Encoding"), F("gzip"));')
            lines.append(f'    r->addHeader(F("Cache-Control"), F("no-cache"));')
            lines.append(f'    req->send(r);')
            lines.append(f'  }});')
            lines.append('')

    # Do NOT register / here — firmware handles it with LittleFS/SD → PROGMEM fallback
    lines.append('}')
    lines.append('')

    out = '\n'.join(lines)
    with open(OUT_FILE, 'w') as f:
        f.write(out)

    saved = total_raw - total_gz
    print(f"\n✓ Written: admin_panel.h")
    print(f"  Files  : {len(files)}")
    print(f"  Raw    : {total_raw:,} bytes ({total_raw//1024} KB)")
    print(f"  Gzipped: {total_gz:,} bytes ({total_gz//1024} KB)")
    print(f"  Saved  : {saved:,} bytes ({100*saved//total_raw}% reduction)")
    print(f"\nNow just upload the sketch — no LittleFS step needed.")

if __name__ == '__main__':
    main()
